name: dl2-callibrated-lm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - jupyterlab
  - notebook
  - pytorch
  - torchvision
  - transformers
  - datasets
  - tokenizers
  - tqdm
  - pip
